# http://travis-ci.org/#!/diyan/pywinrm
# pyenv used instead of native Python support in Travis CI to:
#  - Make build steps exactly the same on both Linux and Mac OS workers
#  - Make possible to debug build steps on local workstation
#  - Integrate new Python / PyPy releases earlier; pyenv does it with less lag than Travis
language: generic
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pyenv
matrix:
  include:
    # Define 'sudo: false' to run on container-based workers
    - { os: linux, dist: xenial, sudo: false, env: UBUNTU=16.04 PYENV=2.7.16 }
    - { os: linux, dist: xenial, sudo: false, env: UBUNTU=16.04 PYENV=3.5.7 }
    - { os: linux, dist: xenial, sudo: false, env: UBUNTU=16.04 PYENV=3.6.8 }
    - { os: linux, dist: xenial, sudo: false, env: UBUNTU=16.04 PYENV=3.7.3 }
    - { os: linux, dist: xenial, sudo: false, env: UBUNTU=16.04 PYENV=3.8-dev }
    - { os: linux, dist: xenial, sudo: false, env: UBUNTU=16.04 PYENV=pypy2.7-7.1.1 }

# pyenv won't build on current Mac versions without some extra conditional help, try to fix this later...
#    - { os: osx, osx_image: xcode10.2, language: generic, env: OSX=10.14 PYENV=2.7.16 }
#    - { os: osx, osx_image: xcode10.2, language: generic, env: OSX=10.14 PYENV=3.7.3 }

install:
  # Always use latest pyenv but keep installed Python versions in cache
  - rm -rf ~/.pyenv
  - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  - mkdir -p ~/.cache/pyenv/versions
  - which pyenv
  - printenv
  - ln -s ~/.cache/pyenv/versions ~/.pyenv/versions
  - export PATH="$HOME/.pyenv/shims:$HOME/.pyenv/bin:$PATH"
  - export PYENV_ROOT="$HOME/.pyenv"
  - pyenv --version
  - pyenv install --skip-existing $PYENV
  - pyenv global $PYENV
  - pyenv rehash
  - python --version
  - pip --version
  - pip install virtualenv
  - python -m virtualenv ~/.venv
  - source ~/.venv/bin/activate
  - pip install -r requirements-test.txt
  - pip install coveralls
  - pip install .[credssp]
  - pip install .[kerberos]
script:
  - pytest -v --flake8 --cov=winrm --cov-report=term-missing winrm/tests/

after_success:
  - coveralls
